#!/bin/bash

function help(){
    echo "Usage"
}

while [[ $# -gt 0 ]]; do
    case $1 in
        -h | --help | help )
            help
            shift 1
            ;;
        * )
            echo "Unknown command"
            shift 1
            help
            ;;
    esac
done